version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: rentalReview_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"





