version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: rentalreview-postgres
    environment:
      POSTGRES_DB: rentalreviewdb
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"


